name: github action deploy 연습

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: hello world 찍기
        run: echo "hello world"

      - name: 여러문장 작성
        run: |
          echo "테스트"
          echo "여러문장"
          echo "넣어보기"

      - name: github action 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY